---
- name: 'RaBe Zabbix : Agent : Get Vars'
  ansible.builtin.include_vars: "EL{{ ansible_distribution_major_version }}.yml"
  tags:
    - always

# NOTE: We install the package from Foreman provided repos mainly so the zabbix user/group is there for certmonger should it be missing
# Adding more to the installation (like additional agent2 plugins or more binaries) is done in the community.zabbix.zabbix_agent role
- name: 'RaBe Zabbix : Agent : Pre Install Agent2'
  ansible.builtin.yum:
    name: "{{ _radiorabe_zabbix_agent_package_name }}"
    state: "{{ _radiorabe_zabbix_agent_package_state }}"
  tags:
    - role::rabe_zabbix.agent
    - role::rabe_zabbix.agent.preinstall

- name: 'RaBe Zabbix : Agent : Prepare Agent Certificate'
  vars:
    certificate_requests:
      - name: zabbix-agent
        group: zabbix
        ca: ipa
        dns: "{{ foreman.foreman_fqdn }}"
        principal: "zabbix/{{ foreman.foreman_fqdn }}@{{ radiorabe_core_int_hostname | upper }}"
  ansible.builtin.include_role:
    name: "{{ _radiorabe_zabbix_agent_certificate_rolename }}"
  tags:
    - role::rabe_zabbix.agent
    - role::rabe_zabbix.agent.certificates

- name: 'RaBe Zabbix : Agent : Configure Zabbix Agent2'
  vars:
    zabbix_agent2: true
    # installation related
    zabbix_repo_yum: []
    zabbix_install_pip_packages: false
    zabbix_agent_disable_repo: []
    zabbix_agent_install_agent_only: true
    # config
    zabbix_agent_dont_detect_ip: true
    zabbix_agent2_allow_key: "{{ ( __radiorabe_zabbix_agent_allow_key + radiorabe_zabbix_agent_extra_allow_key ) | unique }}"
    # environment specific
    zabbix_agent2_server: "{{ radiorabe_zabbix_agent_server }}"
    zabbix_agent2_serveractive: "{{ radiorabe_zabbix_agent_serveractive }}"
    # tls
    zabbix_agent2_tlsaccept: "{{ _radiorabe_zabbix_agent_zabbix_agent_tls }}"
    zabbix_agent2_tlsconnect: "{{ _radiorabe_zabbix_agent_zabbix_agent_tls }}"
    zabbix_agent2_tlscafile: "{{ _radiorabe_zabbix_agent_zabbix_agent_cafile }}"
    zabbix_agent2_tlscertfile: "{{ _radiorabe_zabbix_agent_zabbix_agent_tlscertfile }}"
    zabbix_agent2_tlskeyfile: "{{ _radiorabe_zabbix_agent_zabbix_agent_tlskeyfile }}"
    zabbix_agent2_tlsservercertissuer: "CN=Certificate Authority,O={{ radiorabe_core_int_hostname | upper }}"
    zabbix_agent2_tlsservercertsubject: "CN={{ radiorabe_zabbix_agent_server }},O={{ radiorabe_core_int_hostname | upper }}"
  ansible.builtin.include_role:
    name: "{{ _radiorabe_zabbix_agent_zabbix_agent_rolename }}"
  tags:
    - role::rabe_zabbix.agent
    - role::rabe_zabbix.agent.zabbix_agent

- name: 'RaBe Zabbix : Agent : Configure Firewall'
  include_role:
    name: "{{ _radiorabe_zabbix_agent_firewall_rolename }}"
  vars:
    firewall:
      - rich_rule: ['rule family="ipv4" source address="{{ lookup("dig", radiorabe_zabbix_agent_server) }}" service name="zabbix-agent" accept']
        zone: service
        state: enabled
  tags:
    - role::rabe_zabbix.agent
    - role::rabe_zabbix.agent.firewall
