namespace: radiorabe
name: rabe_galaxy
version: 0.0.0
readme: README.md
authors:
  - Lucas Bickel <@hairmare>
description: GitOps our Zabbix
license_file: LICENSE
tags:
  - radiorabe
  - zabbix
dependencies:
  community.zabbix: ">=1.9.0"
repository: https://github.com/radiorabe/ansible-collection-rabe_zabbix
documentation: https://github.com/radiorabe/ansible-collection-rabe_zabbix/blob/main/README.md
homepage: hhttps://github.com/radiorabe/ansible-collection-rabe_zabbix
issues: https://github.com/radiorabe/ansible-collection-rabe_zabbix/issues
