---
galaxy_info:
  author: RaBe IT-Reaktion
  description: Manage Zabbix data collection
  issue_tracker_url: https://github.com/radiorabe/ansible-collection-rabe_zabbix/issues
  license: AGPL-3.0-only
  min_ansible_version: "2.14"
  platforms:
    - name: EL
      versions:
        - all
    - name: Fedora
      version:
        - all
  galaxy_tags:
    - radiorabe
    - zabbix
