---
- name: "RaBe Zabbix : Config : Authentication"
  vars:
    ansible_network_os: community.zabbix.zabbix
    ansible_connection: httpapi
    ansible_httpapi_port: 443
    ansible_httpapi_use_ssl: true
    ansible_zabbix_url_path: ""
    ansible_host: "{{ zabbix_api_server_url }}"
  community.zabbix.zabbix_authentication:
    ldap_auth_enabled: true
    ldap_case_sensitive: true
    jit_provision_interval: 356d
    disabled_usrgroup: Disabled
