---
- name: "RaBe Zabbix : Config : User Groups : Generate List of all Groups"
  ansible.builtin.set_fact:
    _radiorabe_zabbix_zabbix_user_groups_full_list: >-
      {{ (radiorabe_zabbix_categories | map('regex_replace', '^', radiorabe_zabbix_prefix) | map('regex_replace', '$', ' - P1') | list) +
         (radiorabe_zabbix_categories | map('regex_replace', '^', radiorabe_zabbix_prefix) | map('regex_replace', '$', ' - P2') | list) +
         (radiorabe_zabbix_categories | map('regex_replace', '^', radiorabe_zabbix_prefix) | map('regex_replace', '$', ' - P3') | list) +
         [radiorabe_zabbix_prefix + radiorabe_zabbix_mod_name + ' - P1', radiorabe_zabbix_prefix + radiorabe_zabbix_mod_name + ' - P2'] }}

- name: "RaBe Zabbix : Config : User Groups : Add User Group"
  vars:
    ansible_network_os: community.zabbix.zabbix
    ansible_connection: httpapi
    ansible_httpapi_port: 443
    ansible_httpapi_use_ssl: true
    ansible_zabbix_url_path: ""
    ansible_host: "{{ zabbix_api_server_url }}"
  with_items: "{{ _radiorabe_zabbix_zabbix_user_groups_full_list }}"
  community.zabbix.zabbix_usergroup:
    state: present
    name: "Users of {{ item }}"
