name: Release

on:
  release:
    types:
      - published

jobs:
  call-workflow:
    uses: radiorabe/actions/.github/workflows/release-ansible-collection.yaml@479996126a091287dc3fd349786f6f8a6dd1b23c # v0.42.0
    secrets:
      GALAXY_API_KEY: ${{ secrets.GALAXY_API_KEY }}
