name: Release

on:
  release:
    types:
      - published

jobs:
  call-workflow:
    uses: radiorabe/actions/.github/workflows/release-ansible-collection.yaml@b37e51397726092d8462a2a9b676ea5a5e3a8deb # v0.44.1
    secrets:
      GALAXY_API_KEY: ${{ secrets.GALAXY_API_KEY }}
