name: Release

on:
  release:
    types:
      - published

jobs:
  call-workflow:
    uses: radiorabe/actions/.github/workflows/release-ansible-collection.yaml@c7aef9928f610ec51b44f84debf2321189276d54 # v0.41.3
    secrets:
      GALAXY_API_KEY: ${{ secrets.GALAXY_API_KEY }}
